# Original:  zinc-GRIT-2000.yaml
out_dir: results
metric_best: mae
metric_agg: argmin
tensorboard_each_run: False  # Log to Tensorboard each run
accelerator: "cuda:0"
num_workers: 4
mlflow:
  use: False
  project: async_pe
  name: zinc-GatedGCN-noPE
wandb:
  use: True
  project: async_pe
  name: ZINC-GatedGCN-noPE
  entity: tkrappel-eth-zurich
dataset:
  format: PyG-ZINC
  name: subset
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode #+EquivStableLapPE
  node_encoder_num_types: 28 # actually 21 in Zinc-12k, 28 in Zinc-full
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 4
  edge_encoder_bn: False
  centrality_min: 0
  centrality_max: 1 # needs to be set to correctly reflect the dataset
posenc_EquivStableLapPE:
  enable: False
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 28
  raw_norm_type: none
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  enable_ckpt: True  # Checkpointing can now be disabled to save I/O when e.g. just benchmarking.
  ckpt_best: True  # WARNING: Checkpoint every epoch a better model is found may increase I/O significantly.
  ckpt_clean: True # Delete old ckpt each time.
model:
  type: custom_gnn
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
  alpha: 0.95 # synchronous: 1.0
  alpha_eval_flag: a # inference: a: use alpha values, p: bernoulli (as in training), n: synchronous update
  centrality_range: 0 # 0: no centrality information considered
  use_coloring: False
gnn: # decoder --> san_graph = MLP + pooling
  head: san_graph
  layers_pre_mp: 0
  layers_mp: 4
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  layer_type: gatedgcnconv
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 1e-3
  max_epoch: 500
  num_warmup_epochs: 50
  scheduler: cosine_with_warmup
  min_lr: 1e-6
