out_dir: results
metric_best: accuracy
tensorboard_each_run: True  # Log to Tensorboard each run
accelerator: "cuda:0"
repeat: 4
num_workers: 4
mlflow:
  use: False
  project: Exp
  name: OGBN-ARXIV-GRITSparse-RWSE
wandb:
  use: True
  project: "PEGT"
  name: "OGBN-ARXIV-GRITSparse-RWSE"
  entity: jiaqing
dataset:
  format: OGB
  name: ogbn-arxiv
  task: node
  task_type: classification
  transductive: False
  node_encoder: False
  node_encoder_name: LinearNode+RWSE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: DummyEdge
  edge_encoder_bn: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,17)
  model: Linear
  dim_pe: 8
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 1
  eval_period: 1
  ckpt_period: 100
model:
  type: GritTransformer
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gt:
  layer_type: GritTransformer # some other options: Exphormer,CustomGatedGCN+Exphormer,  GINE+Exphormer, GINE, GINE__exp
  layers: 4
  n_heads: 8
  dim_hidden: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.1
  attn_dropout: 0.1
  layer_norm: False
  batch_norm: True
  sparse: True
gnn:
  head: inductive_node
  layers_pre_mp: 1
  # layers_mp: 3
  layers_post_mp: 1
  dim_inner: 64
  layer_type: generalconv
  stage_type: stack
  batchnorm: True
  act: relu
  dropout: 0.1
  agg: add
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-3
  base_lr: 0.001
  max_epoch: 600
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5