out_dir: results
metric_best: ap
accelerator: "cuda:0"
num_workers: 4
mlflow:
  use: False
  project: Exp
  name: peptides-func-GatedGCN-SignNet
wandb:
  use: True
  project: "PEGT"
  name: "peptides-func-GatedGCN-SignNet"
  entity: jiaqing
dataset:
  format: OGB
  name: peptides-functional
  task: graph
  task_type: classification_multilabel
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+SignNet
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_SignNet:
  dim_pe: 16
  eigen:
    eigvec_norm: L2
    laplacian_norm: sym
    max_freqs: 16
  enable: True
  layers: 4
  model: MLP
  n_heads: 4
  pass_as_var: false
  phi_hidden_dim: 76
  phi_out_dim: 4
  post_layers: 2
  raw_norm_type: none
train:
  mode: custom
  batch_size: 200
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_gnn
  loss_fun: cross_entropy
  graph_pooling: mean
gnn:
  head: mlp_graph
  layers_pre_mp: 0
  layers_mp: 10
  layers_post_mp: 3
  dim_inner: 95
  layer_type: gatedgcnconv
  act: gelu
  residual: True
  dropout: 0.1
optim:
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 250
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 20