out_dir: results
metric_best: accuracy
tensorboard_each_run: True  # Log to Tensorboard each run
accelerator: "cuda:0"
num_workers: 4
mlflow:
  use: False
  project: Exp
  name: limitsone-GRIT-RWSE
wandb:
  use: True
  project: "PEGT-Synthetic"
  name: "limitsone-GRIT-RWSE"
  entity: jiaqing
dataset:
  pe_transform_on_the_fly: False # compute PE on the fly to save memory when launching many experiments in parallel
  format: Synthetic
  name: limitsone
  task: node
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: LinearNode+RWSE
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: LinearEdge
  edge_encoder_bn: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 10
  raw_norm_type: BatchNorm

train:
  mode: custom
  batch_size: 1
  eval_period: 1
  ckpt_period: 100
model:
  type: GritTransformer
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gt:  # Hyperparameters optimized for up to ~500k budget.
  layer_type: GritTransformer
  layers: 10
  n_heads: 8
  dim_hidden: 52 # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.2
  layer_norm: False
  batch_norm: True
  sparse: False
  update_e: False
  attn:
    clamp: 5.
    act: 'relu'
    full_attn: True
    edge_enhance: True
    O_e: True
    norm_e: True
    fwl: False
gnn:
  dim_edge: 52
  head: default
  layers_pre_mp: 0
  layers_mp: 4
  layers_post_mp: 3
  dim_inner: 52  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: False
  act: relu
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5