out_dir: results
metric_best: accuracy-SBM
tensorboard_each_run: True  # Log to Tensorboard each run
accelerator: "cuda:0"
mlflow:
  use: False
  project: Exp
  name: pattern-GRIT-RRWP
wandb:
  use: False
  project: PATTERN
dataset:
  format: PyG-GNNBenchmarkDataset
  name: PATTERN
  task: graph
  task_type: classification
  transductive: False
  split_mode: standard
  node_encoder: True
  node_encoder_name: LinearNode
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: DummyEdge
  edge_encoder_bn: False
posenc_RRWP:
  enable: True
  ksteps: 21
  add_identity: True
  add_node_attr: False
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: NAGphormer
  loss_fun: weighted_cross_entropy
  edge_decoding: dot
gt:
  layer_type: NAGphormer
  hops: 7
  n_class: 1
  dim_hidden: 64
  pe_dim: 4
  num_heads: 8
  dropout: 0.0
  num_layers: 1
  attention_dropout_rate: 0.1
gnn:
  dim_edge: 64
  head: inductive_node
  layers_pre_mp: 0
  layers_post_mp: 3
  dim_inner: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.0005
  max_epoch: 100
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5