out_dir: results
metric_best: accuracy
tensorboard_each_run: True  # Log to Tensorboard each run
accelerator: "cuda:0"
num_workers: 4
pad_to_full_graph: True
mlflow:
  use: False
  project: Exp
  name: skipcircles-GINFull-GCKN
wandb:
  use: True
  project: "PEGT-Synthetic"
  name: "skipcircles-GINFull-GCKN"
  entity: jiaqing
dataset:
  pe_transform_on_the_fly: False # compute PE on the fly to save memory when launching many experiments in parallel
  format: Synthetic
  name: skipcircles
  task: graph
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: LinearNode+GCKN
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: LinearEdge
  edge_encoder_bn: False
posenc_GCKN:
  enable: True
  normalization: None
  beta: 1 # 0.5 for method "pRWSE"
  method: "diffusion"
  use_edge_attr: False
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 10
  layers: 4
  n_heads: 4  # Only used when `posenc.model: Transformer`
  raw_norm_type: none
train:
  mode: custom
  batch_size: 10
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gnn:
  head: default
  layers_pre_mp: 0
  layers_mp: 4
  layers_post_mp: 3
  dim_inner: 52  # `gt.dim_hidden` must match `gnn.dim_inner`
  layer_type: gin_conv
  batchnorm: False
  act: relu
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5