defaults:
  - _self_
  - dataset: ${experiment}
  - experiment: zinc
  - experiment/model: null
  - mode: default

debug: false
seed: 0
test_runs: 5
outdir_prefix: outputs
outdir: 
  "${outdir_prefix}/${dataset.name}\
  /${training.lr}_${training.weight_decay}\
  /${model.name}_${model.dropout}_${model.global_pool}\
  /${seed}"

compute:
  accelerator: auto
  precision: 32

training:
  loss: ${dataset.loss}
  batch_size: 32
  epochs: 100
  iterations: null
  lr: 0.002
  lr_schedule: cosine
  weight_decay: 0.0
  warmup: 10
  num_workers: 4
  pin_memory: true

model:
  in_node_dim: ${dataset.in_node_dim}
  num_class: ${dataset.num_class}
  in_edge_dim: ${dataset.in_edge_dim}
  node_embed: false
  edge_embed: false
  local_mp_type: gin
  global_mp_type: None
  dropout: 0.0
  node_out: true
  global_pool: mean
  head: mlp

logs:
  csv_flag: False
  prefix: logs/${dataset.name}/${model.name}/${seed}
  path: ${logs.prefix}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
  wandb_name:
    "${model.name}/${dataset.name}/${model.alpha}\
    /${model.alpha_eval_flag}/${model.num_layers}/\
    r:${model.recurrent}/\
    ${now:%Y-%m-%d}_${now:%H-%M-%S}"

# output directory, generated dynamically on each run
hydra:
  run:
    dir: ${logs.path}
  sweep:
    dir: ${logs.prefix}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}
