out_dir: results
accelerator: "cuda:0"
metric_best: f1
wandb:
  use: True
  project: async_pe
  name: "COCO-GatedGCN-noPE"
  entity: tkrappel-eth-zurich
dataset:
  dir: ../datasets
  format: PyG-COCOSuperpixels
  name: edge_wt_region_boundary
  slic_compactness: 30
  task: graph  # Even if VOC is node-level task, this needs to be set as 'graph'
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: COCONode #+EquivStableLapPE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: COCOEdge
  edge_encoder_bn: False
posenc_EquivStableLapPE:
  enable: False
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
train:
  mode: custom
  batch_size: 16
  eval_period: 1
  ckpt_period: 100
  eval_smoothing_metrics: True
async_update:
  metric: centrality
  metric_min: 0
  metric_max: 0.75 # needs to be set to correctly reflect the dataset and the metric
  metric_range: 0.0
  metric_pos: True
  alpha: 1.0
  alpha_node_flag: a
  alpha_edge_flag: a
  use_coloring: False
model:
  type: custom_gnn
  loss_fun: weighted_cross_entropy
gnn:
  head: inductive_node
  layers_pre_mp: 0
  layers_mp: 6
  layers_post_mp: 1
  dim_inner: 120
  layer_type: gatedgcnconv
  act: gelu
  residual: True
  dropout: 0.1
optim:
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10