out_dir: results
metric_best: mae
metric_agg: argmin
accelerator: "cuda:0"
mlflow:
  use: False
  project: Exp
  name: peptides-struct-GRIT-SignNet
wandb:
  use: True
  project: "PEGT"
  name: "peptides-struct-GRIT-SignNet"
  entity: jiaqing
dataset:
  format: OGB
  name: peptides-structural
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+SignNet
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_SignNet:
  dim_pe: 24
  eigen:
    eigvec_norm: L2
    laplacian_norm: sym
    max_freqs: 10
  enable: True
  layers: 4
  model: MLP
  n_heads: 4
  pass_as_var: false
  phi_hidden_dim: 64
  phi_out_dim: 4
  post_layers: 2
  raw_norm_type: none
train:
  mode: custom
#  batch_size: 32
  batch_size: 16
  eval_period: 1
  ckpt_period: 100
model:
  type: GritTransformer
  loss_fun: l1
  graph_pooling: mean
gt:
  layer_type: GritTransformer
  layers: 4
  n_heads: 8
  dim_hidden: 96 # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.05
  attn_dropout: 0.2
  layer_norm: False
  batch_norm: True
  sparse: False
  attn:
    clamp: 5.
    act: 'relu'
    full_attn: True
    edge_enhance: False
    O_e: True
    norm_e: True
    signed_sqrt: True
gnn:
  head: default
  layers_pre_mp: 0
  layers_post_mp: 2 # Not used when `gnn.head: san_graph`
  dim_inner: 96  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0003
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10