name: ogbg-molhiv
cls_name: ogb.graphproppred.PygGraphPropPredDataset
path: ./datasets/OGBGDataset
in_node_dim: atom
in_edge_dim: bond
num_class: 1
loss: bce # ce expects one output per class
metric: ogbg-rocauc