out_dir: results
metric_best: mae
metric_agg: argmin
num_workers: 4
mlflow:
  use: False
  project: Exp
  name: peptides-struct-GatedGCN-SignNet
wandb:
  use: True
  project: "PEGT"
  name: "peptides-struct-GatedGCN-SignNet"
  entity: jiaqing
dataset:
  format: OGB
  name: peptides-structural
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+SignNet
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_SignNet:
  dim_pe: 16
  eigen:
    eigvec_norm: L2
    laplacian_norm: sym
    max_freqs: 16
  enable: True
  layers: 4
  model: MLP
  n_heads: 4
  pass_as_var: false
  phi_hidden_dim: 96
  phi_out_dim: 4
  post_layers: 2
  raw_norm_type: none
train:
  mode: custom
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
  eval_smoothing_metrics: True
model:
  type: custom_gnn
  loss_fun: l1
  graph_pooling: mean
gnn:
  head: mlp_graph
  layers_pre_mp: 0
  layers_mp: 8
  layers_post_mp: 3
  dim_inner: 100
  layer_type: gatedgcnconv
  act: gelu
  residual: True
  dropout: 0.1
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 250
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5