out_dir: results
metric_best: ap
accelerator: "cuda:0"
num_workers: 4
mlflow:
  use: False
  project: Exp
  name: peptides-func-GPS-RRWP
wandb:
  use: True
  project: "PEGT"
  name: "peptides-func-GPS-RRWP"
  entity: jiaqing
dataset:
  pe_transform_on_the_fly: True
  format: OGB
  name: peptides-functional
  task: graph
  task_type: classification_multilabel
  transductive: False
  node_encoder: True
  node_encoder_name: Atom
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_RRWP:
  enable: True
  ksteps: 16
  add_identity: True
  add_node_attr: False
  add_inverse: False
train:
  mode: custom
  batch_size: 200
  eval_period: 1
  ckpt_period: 100
model:
  type: GPSModel
  loss_fun: cross_entropy
  graph_pooling: mean
gt:
  layer_type: CustomGatedGCN+Transformer
  layers: 6
  n_heads: 4
  dim_hidden: 76  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.1
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: True
gnn:
  head:  mlp_graph
  layers_pre_mp: 0
  layers_post_mp: 2  # Not used when `gnn.head: san_graph`
  dim_inner: 76  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: gelu
  dropout: 0.1
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 250
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
