out_dir: results
metric_best: mae
metric_agg: argmin
num_workers: 4
mlflow:
  use: False
  project: Exp
  name: peptides-struct-Exphormer-RRWP
wandb:
  use: True
  project: "PEGT"
  name: "peptides-struct-Exphormer-RRWP"
  entity: jiaqing
dataset:
  pe_transform_on_the_fly: True
  format: OGB
  name: peptides-structural
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: Atom #+EquivStableLapPE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_RRWP:
  enable: True
  ksteps: 16
  add_identity: True
  add_node_attr: False
  add_inverse: False
prep:
  exp: True
  exp_deg: 5
  use_exp_edges: False
  add_edge_index: True # Set True if you want to add real edges beside expander edges
  num_virt_node: 6 # Set True if you want to add global node connections beside expander edges
train:
  mode: custom
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
model:
  type: MultiModel
  loss_fun: l1
  graph_pooling: mean
gt:
  layer_type: CustomGatedGCN+Exphormer
  layers: 4
  n_heads: 4
  dim_hidden: 88  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.12
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: True
gnn:
  head: default
  layers_pre_mp: 0
  layers_post_mp: 1  # Not used when `gnn.head: san_graph`
  dim_inner: 88  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.12
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0003
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
