out_dir: results
accelerator: "cuda:0"
metric_best: mrr
num_workers: 4
mlflow:
  use: False
  project: async_pe
  name: pcqm4m-contact-GINE-noPE
wandb:
  use: True
  project: async_pe
  name: "pcqm4m-contact-GINE-noPE"
  entity: wandb_entity
dataset:
  dir: ./datasets
  format: OGB
  name: PCQM4Mv2Contact-shuffle
  task: graph  # PCQM4Mv2Contact is edge-level task, but because it is inductive, set to 'graph'
  task_type: classification
  resample_negative: True
  transductive: False
  node_encoder: True
  node_encoder_name: Atom #+LapPE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
  centrality_min: 0
  centrality_max: 1.0 # needs to be set to correctly reflect the dataset
train:
  mode: custom
  batch_size: 500
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  alpha: 1.0 # synchronous: 1.0, higher alpha -> update more nodes in one iteration
  alpha_node_flag: a # inference (nodes): a: use alpha values, p: bernoulli (as in training), n: synchronous update
  alpha_edge_flag: a # inference (edges): a: average of end nodes, m: maximum alpha of the two end nodes
  centrality_range: 0.0 # 0: no centrality information considered
  use_coloring: False
gnn:
  head: inductive_edge
  layers_pre_mp: 0
  layers_mp: 8
  layers_post_mp: 1
  dim_inner: 215
  batchnorm: True
  layer_type: gineconv
  act: gelu
  residual: True
  dropout: 0.1
  batchnorm: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 100
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5